### PR TITLE
Added columns for Timestamp, Product Price and shop name

### PR DESCRIPTION
**Pull request by michaelaguiar**
Added new columns and updated the available columns for domain_shopping.

### CODE REVIEW

**Comment by michaelaguiar** [comment]
A bunch of updates to add support for collecting backlinks through their API.  Please let me know if you have any questions / recommendations.

One thing I was unsure about, was how to handle different endpoints.  Currently, they are mapped by API version, but backlinks have a different endpoint.  I added a new class for determining APIType that returns "analytics" for these TYPES -- which points them to the right endpoint.

Now that I have the foundation for backlinks in there, I am going to add the methods / definitions for the remainder of Backlinks from the API.

Looking forward to any feedback!

**Review by andywaite — COMMENTED** [review]
Looks like some really good additions here. The TypeAPITypeMap makes sense, although I probably would have tried to name it something clearer. I'm trying to understand why you removed the columns from the request definitions?

**Comment by michaelaguiar** [comment]
Yea definitely need a better name for TypeAPITypeMap, any ideas?

Which definitions are you referring too? 

Also, I updated the domain_ranks definition to include:
  
- COLUMN_OVERVIEW_PLA_UNIQUES
- COLUMN_OVERVIEW_PLA_KEYWORDS

But, for some reason during the test with key "demo key", it excludes these headers and fails because 9 columns are returned instead of the expected 11?

**Comment by andywaite** [comment]
screenshot from 2018-04-30 17-23-31

These are the definitions I meant.

**Comment by andywaite** [comment]
Closing as it's been so long and there are conflicts

**Pull request closed without merging**
