### PR TITLE
Update Guzzle Library

### PR DESCRIPTION
**Pull request by michaelaguiar**
v3 is becoming deprecated.  Updated to 6.1

### CODE REVIEW

**Comment by michaelaguiar** [comment]
Any update on this?

I will be making another pull request shortly with the addition of a few more API functions.

**Comment by andywaite** [comment]
@michaelaguiar thanks

**Comment by jrosell** [comment]
@andywaite @michaelaguiar i try it for a new project and i get error that refrence to Guzzle3.

Class 'Guzzle\Http\Client' not found

**Comment by michaelaguiar** [comment]
@jrosell I believe it's actually GuzzleHttp\Client that you need to use.  I have an updated fork here: https://github.com/aliasproject/semrush-api  -- you can try this one.  I was making a lot of updates, and needed the repo to be updated quicker, so I just made a fork.

**Comment by jrosell** [comment]
Thanks i was starting somethink on my own https://github.com/jrosell/semrush-api/commit/66e0e2760436f0db964327869c3fb99e6afc4995

**Comment by michaelaguiar** [comment]
Try out my fork, might be just what you needed.  Let me know if you have any issues.  You can even fork my branch if you want, and submit a push request for any bugs you find and ill merge right away.

**Pull request merged**
